/**
 * Swagger configuration module.
 *
 * Hybrid approach:
 *  - Automatically discovers all Express controllers at runtime.
 *  - Merges them with manually documented @swagger JSDoc blocks.
 *  - Undocumented controllers still appear with a default stub.
 *  - Documented controllers override the stub with full OpenAPI definitions.
 */

import swaggerUi from "swagger-ui-express";
import swaggerJsdoc from "swagger-jsdoc";
import listEndpoints from "express-list-endpoints";
import deepmerge from "deepmerge";

/**
 * Base Swagger (OpenAPI 3) configuration.
 * This defines general API metadata and tells swagger-jsdoc
 * where to scan for @swagger annotations.
 */
const swaggerOptions = {
    definition: {
        openapi: "3.0.0",
        info: {
            title: process.env.APP_NAME ?? "Backend-Mid-Specialism",
            version: process.env.APP_VERSION ?? "0.0.1",
            description: "API documentation",
        },
    },

    /**
     * Files that contain @swagger JSDoc blocks.
     * Adjust paths if router structure changes.
     */
    apis: ["./src/routers/**/*.js", "./src/routers/*.js"],
};

/**
 * Default OpenAPI operation stub.
 *
 * Used when an endpoint has NO @swagger documentation.
 * Ensures that every route still appears in Swagger UI.
 */
const openApiEndpointSpecStub = {
    tags: ["Undocumented"],
    responses: {
        200: { description: "OK" },
    },
};

/**
 * swagger-jsdoc generated specification
 * based only on @swagger JSDoc blocks.
 */
const swaggerSpec = swaggerJsdoc(swaggerOptions);

/**
 * Swagger UI static middleware.
 */
const swaggerServe = swaggerUi.serve;

/**
 * Generates OpenAPI "paths" object automatically
 * by inspecting the Express app router stack.
 *
 * @param {import("express").Application} app - Express application instance
 * @returns {object} OpenAPI-compatible paths object
 *
 * Example output:
 * {
 *   "/api/users": {
 *     get: { ... },
 *     post: { ... }
 *   }
 * }
 */
const generateOpenApiSpecs = (app) => {
    const specs = {};

    for (const ep of listEndpoints(app)) {
        // Ensure path object exists
        specs[ep.path] ??= {};

        for (const method of ep.methods) {
            const m = method.toLowerCase();

            // Only add stub if not already defined
            specs[ep.path][m] ??= {
                ...openApiEndpointSpecStub,
                summary: `Undocumented: ${method} ${ep.path}`,
            };
        }
    }

    return specs;
};

/**
 * Initializes Swagger UI with merged specification.
 *
 * Steps:
 *  1. Auto-generate path specs from Express routes
 *  2. Merge with swagger-jsdoc output
 *     (Manual @swagger docs override auto stubs)
 *  3. Mount Swagger UI at /docs
 *
 * @param {import("express").Application} app - Express application instance
 */
const swaggerSetup = (app) => {
    const autoGeneratedSpecs = generateOpenApiSpecs(app);

    // Start from the jsdoc spec (source of truth)
    const mergedSpec = { ...swaggerSpec };
    mergedSpec.paths ??= {};

    // Only add stubs where docs are missing
    for (const [path, ops] of Object.entries(autoGeneratedSpecs)) {
        mergedSpec.paths[path] ??= {};
        for (const [method, opSpec] of Object.entries(ops)) {
            mergedSpec.paths[path][method] ??= opSpec; // keep documented op if it exists
        }
    }

    app.use("/docs", swaggerServe, swaggerUi.setup(mergedSpec));
};

export default swaggerSetup;